- header: 'ORGANIZATIONAL PLANNING & IMPLEMENTATION: Please consider a rating of "ten" as always exhibiting this behavior, "five" or "six" as sometimes, and "one" as never.' 
  questions:
    - - range1
      - text: "S/he effectively guides our team/organization in setting PRIMO goals (precise, realistic, inspiring, measurable, and outcome-oriented)."
        self_text: "I effectively guide our team/organization in setting PRIMO goals (precise, realistic, inspiring, measurable, and outcome-oriented)."
        legacy_tag: org_01
    - - range2
      - text: "S/he leads our team/organization in setting goals that really stretch us (bold, push the edge) while still being achievable."
        self_text: "I lead our team/organization in setting goals that really stretch us (bold, push the edge) while still being achievable."
        legacy_tag: org_02
    - - range3
      - text: "S/he ensures buy-in to goals by creating sufficient input and engagement in our planning process."
        self_text: "I ensure buy-in to goals by creating sufficient input and engagement in our planning process."
        legacy_tag: org_03
    - - range4
      - text: "Team members know exactly what we're responsible for."
        self_text: "Team members know exactly what we're responsible for."
        legacy_tag: org_04
    - - range5
      - text: "The quality standards to which our work will be held are clear."
        self_text: "The quality standards to which our work will be held are clear."
        legacy_tag: org_05
    - - range6
      - text: All teams and individuals have clearly defined work plans.
        self_text: All teams and individuals have clearly defined work plans.
        legacy_tag: org_06
    - - range7
      - text: "Everyone's work plans clearly link back to our mission."
        self_text: "Everyone's work plans clearly link back to our mission."
        legacy_tag: org_07
    - - range8
      - text: Our work plans are used regularly by everyone as effective guides to daily priorities and action.
        self_text: Our work plans are used regularly by everyone as effective guides to daily priorities and action.
        legacy_tag: org_08
    - - range9
      - text: We use measurements effectively to improve our performance.
        self_text: We use measurements effectively to improve our performance.
        legacy_tag: org_09
    - - range10
      - text: "We regularly utilize an effective process for evaluating our organization's progress against our stated goals."
        self_text: "We regularly utilize an effective process for evaluating our organization's progress against our stated goals."
        legacy_tag: org_10
    - - range11
      - text: "The team has an effective system for tracking commitments that supports everyone's impeccable accountability."
        self_text: "The team has an effective system for tracking commitments that supports everyone's impeccable accountability."
        legacy_tag: org_11
    - - range12
      - text: "We're totally focused on results rather than activity or how hard we work."
        self_text: "We're totally focused on results rather than activity or how hard we work."
        legacy_tag: org_12
    - - range13
      - text: "We focus our time, energy & resources on getting the priority results most important for the success of our mission."
        self_text: "We focus our time, energy & resources on getting the priority results most important for the success of our mission."
        legacy_tag: org_13
    - - text1
      - text: "What works best about your team's planning and implementation processes?"
        self_text: "What works best about your team's planning and implementation processes?"
        legacy_tag: org_text_1
    - - text2
      - text: "What is the most important thing s/he could do to improve planning and implementation in your organization?"
        self_text: "What is the most important thing you could do to improve planning and implementation in your organization?"
        legacy_tag: org_text_2
- header: 'PERFORMANCE MANAGEMENT: Please consider a rating of "ten" as always exhibiting this behavior, "five" or "six" as sometimes, and "one" as never.'
  questions:
    - - range14
      - text: S/he brings positive energy and enthusiasm to the job of managing performance in my organization.
        self_text: I bring positive energy and enthusiasm to the job of managing performance in my organization.
        legacy_tag: org_14
    - - range15
      - text: "Overall, s/he ensures an effective process of evaluating individual performance."
        self_text: "Overall, I ensure an effective process of evaluating individual performance."
        legacy_tag: org_15
    - - range16
      - text: "We get the support that we need from him/her."
        self_text: "Others get the support that they need from you."
        legacy_tag: org_16
    - - range17
      - text: S/he offers considerably more reinforcement of what people are doing right than critique of what needs improvement.
        self_text: I offer considerably more reinforcement of what people are doing right than critique of what needs improvement.
        legacy_tag: org_17
    - - range18
      - text: "Team members regularly give each other helpful, performance-related feedback."
        self_text: "Team members regularly give each other helpful, performance-related feedback."
        legacy_tag: org_18
    - - range19
      - text: S/he strongly models accountability in her/his behavior (accountability= doing what we say we would do in the time we said we would do it).
        self_text: I strongly model accountability in my behavior (accountability= doing what we say we would do in the time we said we would do it).
        legacy_tag: org_19
    - - range20
      - text: "Team members deliver on their work commitments impeccably within the promised time frame."
        self_text: "Team members deliver on their work commitments impeccably within the promised time frame."
        legacy_tag: org_20
    - - range21
      - text: S/he holds team members accountable to the commitments we make.
        self_text: I hold team members accountable to the commitments we make.
        legacy_tag: org_21
    - - range22
      - text: Our whole team holds each other accountable to the commitments we make.
        self_text: Our whole team holds each other accountable to the commitments we make.
        legacy_tag: org_22
    - - range23
      - text: We manage our agreements and commitments so that we can meet them in a sustainable way.
        self_text: We manage our agreements and commitments so that we can meet them in a sustainable way.
        legacy_tag: org_23
    - - range24
      - text: We hold very high quality standards for our work.
        self_text: We hold very high quality standards for our work.
        legacy_tag: org_24
    - - range25
      - text: S/he proactively and directly confronts performance issues in a timely way.
        self_text: I proactively and directly confront performance issues in a timely way.
        legacy_tag: org_25
    - - range26
      - text: Team members have the information and tools we need to be successful.
        self_text: Team members have the information and tools we need to be successful.
        legacy_tag: org_26
    - - range27
      - text: We have a hiring process that generates excellent hires in our organization.
        self_text: We have a hiring process that generates excellent hires in our organization.
        legacy_tag: org_27
    - - range28
      - text: Our salary structure and benefits are sufficient to attract and retain the best people.
        self_text: Our salary structure and benefits are sufficient to attract and retain the best people.
        legacy_tag: org_28
    - - range29
      - text: "We receive the training, development and coaching we need to keep improving our skills and capacity."
        self_text: "We receive the training, development and coaching we need to keep improving our skills and capacity."
        legacy_tag: org_29
    - - range30
      - text: "We receive the training, development and mentoring we need to advance our career."
        self_text: "We receive the training, development and mentoring we need to advance our career."
        legacy_tag: org_30
    - - text3
      - text: "What is his/her greatest strength in managing performance?"
        self_text: "What is your greatest strength in managing performance?"
        legacy_tag: org_text_3
    - - text4
      - text: "What is his/her greatest need for improvement in managing performance?"
        self_text: "What is your greatest need for improvement in managing performance?"
        legacy_tag: org_text_4
