- header: section header test
  questions:
    - - range1
      - text: test2 range question 1 text
        self_text: test2 range question 1 self_text
        legacy_tag: tage1_legacy_tag
    - - range2
      - text: how many ducks do they have
        self_text: how many ducks do you have?
        legacy_tag: ducks
    - - text1
      - text: What is the question for text 1
        self_text: What is YOUR question for text 1
        legacy_tag: weaknesses
    - - text2
      - text: Is it turtles all the way down?
        self_text: why are you reading this?
        legacy_tag: turtles
